/* TA-LIB Copyright (c) 1999-2025, Mario Fortier
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or
 * without modification, are permitted provided that the following
 * conditions are met:
 *
 * - Redistributions of source code must retain the above copyright
 *   notice, this list of conditions and the following disclaimer.
 *
 * - Redistributions in binary form must reproduce the above copyright
 *   notice, this list of conditions and the following disclaimer in
 *   the documentation and/or other materials provided with the
 *   distribution.
 *
 * - Neither name of author nor the names of its contributors
 *   may be used to endorse or promote products derived from this
 *   software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/* List of contributors:
 *
 *  Initial  Name/description
 *  -------------------------------------------------------------------
 *  BUD      Bud Davis
 *
 *
 * Change history:
 *
 *  MMDDYY BY   Description
 *  -------------------------------------------------------------------
 *  010625 BUD  Creation
 *
 */

/**** START GENCODE SECTION 1 - DO NOT DELETE THIS LINE ****/
/* All code within this section is automatically
 * generated by gen_code. Any modification will be lost
 * next time gen_code is run.
 */
/* Generated */ 
/* Generated */ #if defined( _MANAGED )
/* Generated */    #include "TA-Lib-Core.h"
/* Generated */    #define TA_INTERNAL_ERROR(Id) (RetCode::InternalError)
/* Generated */    namespace TicTacTec { namespace TA { namespace Library {
/* Generated */ #elif defined( _JAVA )
/* Generated */    #include "ta_defs.h"
/* Generated */    #include "ta_java_defs.h"
/* Generated */    #define TA_INTERNAL_ERROR(Id) (RetCode.InternalError)
/* Generated */ #elif defined( _RUST )
/* Generated */    #include "ta_defs.h"
/* Generated */    #define TA_INTERNAL_ERROR(Id) (RetCode.InternalError)
/* Generated */    impl Core {
/* Generated */ #else
/* Generated */    #include <string.h>
/* Generated */    #include <math.h>
/* Generated */    #include "ta_func.h"
/* Generated */ #endif
/* Generated */ 
/* Generated */ #ifndef TA_UTILITY_H
/* Generated */    #include "ta_utility.h"
/* Generated */ #endif
/* Generated */ 
/* Generated */ #ifndef TA_MEMORY_H
/* Generated */    #include "ta_memory.h"
/* Generated */ #endif
/* Generated */ 
/* Generated */ #define TA_PREFIX(x) TA_##x
/* Generated */ #define INPUT_TYPE   double
/* Generated */ 
/* Generated */ #if defined( _MANAGED )
/* Generated */ int Core::BrvrLookback( void )
/* Generated */ 
/* Generated */ #elif defined( _JAVA )
/* Generated */ public int brvrLookback( void )
/* Generated */ 
/* Generated */ #elif defined( _RUST )
/* Generated */ pub fn brvr_lookback() -> i32
/* Generated */ #else
/* Generated */ TA_LIB_API int TA_BRVR_Lookback( void )
/* Generated */ 
/* Generated */ #endif
/**** END GENCODE SECTION 1 - DO NOT DELETE THIS LINE ****/
{
   /* insert local variable here */

/**** START GENCODE SECTION 2 - DO NOT DELETE THIS LINE ****/
/* Generated */ #ifndef TA_FUNC_NO_RANGE_CHECK
/* Generated */    /* No optional parameters to validate */
/* Generated */ #endif /* TA_FUNC_NO_RANGE_CHECK */
/**** END GENCODE SECTION 2 - DO NOT DELETE THIS LINE ****/

   /* insert lookback code here. */
	/* Lookback is 20 candles (max of body avg period 10 and volume avg period 20) */
	return 20;
}

/**** START GENCODE SECTION 3 - DO NOT DELETE THIS LINE ****/
/*
 * TA_BRVR - Body Ratio and Volume Ratio
 * 
 * Input  = Open, High, Low, Close, Volume
 * Output = double, double
 * 
 * Body ratio is compared to average body length of 10 previous candles.
 * Positive for bullish candle, negative for bearish candle.
 * Volume ratio is compared to average volume of 20 previous candles.
 * Always positive.
 * 
 */
/* Generated */ 
/* Generated */ #if defined( _MANAGED ) && defined( USE_SUBARRAY )
/* Generated */ enum class Core::RetCode Core::Brvr( int    startIdx,
/* Generated */                                             int    endIdx,
/* Generated */                                             SubArray<double>^ inOpen,
/* Generated */                                             SubArray<double>^ inHigh,
/* Generated */                                             SubArray<double>^ inLow,
/* Generated */                                             SubArray<double>^ inClose,
/* Generated */                                             SubArray<double>^ inVolume,
/* Generated */                                             [Out]int%    outBegIdx,
/* Generated */                                             [Out]int%    outNBElement,
/* Generated */                                             SubArray<double>^  outBodyRatio,
/* Generated */                                             SubArray<double>^  outVolumeRatio )
/* Generated */ #elif defined( _MANAGED )
/* Generated */ enum class Core::RetCode Core::Brvr( int    startIdx,
/* Generated */                                             int    endIdx,
/* Generated */                                             cli::array<double>^ inOpen,
/* Generated */                                             cli::array<double>^ inHigh,
/* Generated */                                             cli::array<double>^ inLow,
/* Generated */                                             cli::array<double>^ inClose,
/* Generated */                                             cli::array<double>^ inVolume,
/* Generated */                                             [Out]int%    outBegIdx,
/* Generated */                                             [Out]int%    outNBElement,
/* Generated */                                             cli::array<double>^  outBodyRatio,
/* Generated */                                             cli::array<double>^  outVolumeRatio )
/* Generated */ #elif defined( _JAVA )
/* Generated */ public RetCode brvr( int    startIdx,
/* Generated */                             int    endIdx,
/* Generated */                             double       inOpen[],
/* Generated */                             double       inHigh[],
/* Generated */                             double       inLow[],
/* Generated */                             double       inClose[],
/* Generated */                             double       inVolume[],
/* Generated */                             MInteger     outBegIdx,
/* Generated */                             MInteger     outNBElement,
/* Generated */                             double        outBodyRatio[],
/* Generated */                             double        outVolumeRatio[] )
/* Generated */ #elif defined( _RUST )
/* Generated */ pub fn brvr(startIdx: usize,
/* Generated */                    endIdx: usize,
/* Generated */                    outBegIdx: &mut usize,
/* Generated */                    outNBElement: &mut usize,
/* Generated */                    outBodyRatio: &mut [f64],
/* Generated */                    outVolumeRatio: &mut [f64]) -> RetCode
/* Generated */ #else
/* Generated */ TA_LIB_API TA_RetCode TA_BRVR( int    startIdx,
/* Generated */                                       int    endIdx,
/* Generated */                                                  const double inOpen[],
/* Generated */                                                  const double inHigh[],
/* Generated */                                                  const double inLow[],
/* Generated */                                                  const double inClose[],
/* Generated */                                                  const double inVolume[],
/* Generated */                                                  int          *outBegIdx,
/* Generated */                                                  int          *outNBElement,
/* Generated */                                                  double        outBodyRatio[],
/* Generated */                                                  double        outVolumeRatio[] )
/* Generated */ #endif
/**** END GENCODE SECTION 3 - DO NOT DELETE THIS LINE ****/
{
   /* Insert local variables here. */
	double BodyPeriodTotal, VolumePeriodTotal;
	int i, outIdx, BodyTrailingIdx, VolumeTrailingIdx, lookbackTotal;

/**** START GENCODE SECTION 4 - DO NOT DELETE THIS LINE ****/
/* Generated */ 
/* Generated */ #ifndef TA_FUNC_NO_RANGE_CHECK
/* Generated */ 
/* Generated */    /* Validate the requested output range. */
/* Generated */ #if defined( _RUST )
/* Generated */    if( endIdx < startIdx ) {
/* Generated */       return ENUM_VALUE(RetCode,TA_OUT_OF_RANGE_END_INDEX,OutOfRangeEndIndex);
/* Generated */    }
/* Generated */ #else
/* Generated */    if( startIdx < 0 ) {
/* Generated */       return ENUM_VALUE(RetCode,TA_OUT_OF_RANGE_START_INDEX,OutOfRangeStartIndex);
/* Generated */    }
/* Generated */    if( (endIdx < 0) || (endIdx < startIdx)) {
/* Generated */       return ENUM_VALUE(RetCode,TA_OUT_OF_RANGE_END_INDEX,OutOfRangeEndIndex);
/* Generated */    }
/* Generated */ #endif
/* Generated */ 
/* Generated */ #if defined( _RUST )
/* Generated */ 
/* Generated */ #else
/* Generated */    #if !defined(_JAVA)
/* Generated */    /* Verify required price component. */
/* Generated */    if(!inOpen||!inHigh||!inLow||!inClose||!inVolume)
/* Generated */       return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */    #endif /* !defined(_JAVA)*/
/* Generated */    #if !defined(_JAVA)
/* Generated */    if( !outBodyRatio )
/* Generated */       return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */    if( !outVolumeRatio )
/* Generated */       return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */    #endif /* !defined(_JAVA) */
/* Generated */ #endif
/* Generated */ #endif /* TA_FUNC_NO_RANGE_CHECK */
/* Generated */ 
/**** END GENCODE SECTION 4 - DO NOT DELETE THIS LINE ****/

   /* Identify the minimum number of price bar needed
	* to calculate at least one output.
	*/

   lookbackTotal = LOOKBACK_CALL(BRVR)();

   /* Move up the start index if there is not
	* enough initial data.
	*/
   if( startIdx < lookbackTotal )
	  startIdx = lookbackTotal;

   /* Make sure there is still something to evaluate. */
   if( startIdx > endIdx )
   {
	  VALUE_HANDLE_DEREF_TO_ZERO(outBegIdx);
	  VALUE_HANDLE_DEREF_TO_ZERO(outNBElement);
	  return ENUM_VALUE(RetCode,TA_SUCCESS,Success);
   }

   /* Do the calculation using tight loops. */
   /* Add-up the initial period for body (10 candles) and volume (20 candles) */
   BodyPeriodTotal = 0;
   VolumePeriodTotal = 0;
   BodyTrailingIdx = startIdx - 10;
   VolumeTrailingIdx = startIdx - 20;

   /* Initialize body sum */
   i = BodyTrailingIdx;
   while( i < startIdx ) {
		BodyPeriodTotal += TA_REALBODY(i);
		i++;
   }

   /* Initialize volume sum */
   i = VolumeTrailingIdx;
   while( i < startIdx ) {
		VolumePeriodTotal += inVolume[i];
		i++;
   }

   i = startIdx;

   /* Proceed with the calculation for the requested range.
	* - Body ratio: current body / average body of 10 previous candles
	*   Positive for bullish (white) candle, negative for bearish (black) candle
	* - Volume ratio: current volume / average volume of 20 previous candles
	*   Always positive
	*/
   outIdx = 0;

   do
   {
		double avgBody = BodyPeriodTotal / 10.0;
		double avgVolume = VolumePeriodTotal / 20.0;
		double currentBody = TA_REALBODY(i);
		double bodyRatio;

		/* Calculate body ratio */
		if( avgBody > 0 )
			bodyRatio = currentBody / avgBody;
		else
			bodyRatio = 0.0;

		/* Make body ratio negative for bearish (black) candles */
		if( TA_CANDLECOLOR(i) == -1 )
			bodyRatio = -bodyRatio;

		/* Calculate volume ratio (always positive) */
		double volumeRatio;
		if( avgVolume > 0 )
			volumeRatio = inVolume[i] / avgVolume;
		else
			volumeRatio = 0.0;

		outBodyRatio[outIdx] = bodyRatio;
		outVolumeRatio[outIdx] = volumeRatio;
		outIdx++;

		/* Update rolling sums */
		BodyPeriodTotal += TA_REALBODY(i) - TA_REALBODY(BodyTrailingIdx);
		VolumePeriodTotal += inVolume[i] - inVolume[VolumeTrailingIdx];
		i++;
		BodyTrailingIdx++;
		VolumeTrailingIdx++;
   } while( i <= endIdx );

   /* All done. Indicate the output limits and return. */
   VALUE_HANDLE_DEREF(outNBElement) = outIdx;
   VALUE_HANDLE_DEREF(outBegIdx)    = startIdx;

   return ENUM_VALUE(RetCode,TA_SUCCESS,Success);
}

/**** START GENCODE SECTION 5 - DO NOT DELETE THIS LINE ****/
/* Generated */ 
/* Generated */ #define  USE_SINGLE_PRECISION_INPUT
/* Generated */ #if !defined( _MANAGED ) && !defined( _JAVA )
/* Generated */    #undef   TA_PREFIX
/* Generated */    #define  TA_PREFIX(x) TA_S_##x
/* Generated */ #endif
/* Generated */ #undef   INPUT_TYPE
/* Generated */ #define  INPUT_TYPE float
/* Generated */ #if defined( _MANAGED ) && defined( USE_SUBARRAY )
/* Generated */ enum class Core::RetCode Core::Brvr( int    startIdx,
/* Generated */                                             int    endIdx,
/* Generated */                                             SubArray<float>^ inOpen,
/* Generated */                                             SubArray<float>^ inHigh,
/* Generated */                                             SubArray<float>^ inLow,
/* Generated */                                             SubArray<float>^ inClose,
/* Generated */                                             SubArray<float>^ inVolume,
/* Generated */                                             [Out]int%    outBegIdx,
/* Generated */                                             [Out]int%    outNBElement,
/* Generated */                                             SubArray<double>^  outBodyRatio,
/* Generated */                                             SubArray<double>^  outVolumeRatio )
/* Generated */ #elif defined( _MANAGED )
/* Generated */ enum class Core::RetCode Core::Brvr( int    startIdx,
/* Generated */                                             int    endIdx,
/* Generated */                                             cli::array<float>^ inOpen,
/* Generated */                                             cli::array<float>^ inHigh,
/* Generated */                                             cli::array<float>^ inLow,
/* Generated */                                             cli::array<float>^ inClose,
/* Generated */                                             cli::array<float>^ inVolume,
/* Generated */                                             [Out]int%    outBegIdx,
/* Generated */                                             [Out]int%    outNBElement,
/* Generated */                                             cli::array<double>^  outBodyRatio,
/* Generated */                                             cli::array<double>^  outVolumeRatio )
/* Generated */ #elif defined( _JAVA )
/* Generated */ public RetCode brvr( int    startIdx,
/* Generated */                             int    endIdx,
/* Generated */                             float        inOpen[],
/* Generated */                             float        inHigh[],
/* Generated */                             float        inLow[],
/* Generated */                             float        inClose[],
/* Generated */                             float        inVolume[],
/* Generated */                             MInteger     outBegIdx,
/* Generated */                             MInteger     outNBElement,
/* Generated */                             double        outBodyRatio[],
/* Generated */                             double        outVolumeRatio[] )
/* Generated */ #elif defined( _RUST )
/* Generated */ pub fn brvr_s(startIdx: usize,
/* Generated */                      endIdx: usize,
/* Generated */                      outBegIdx: &mut usize,
/* Generated */                      outNBElement: &mut usize,
/* Generated */                      outBodyRatio: &mut [f64],
/* Generated */                      outVolumeRatio: &mut [f64]) -> RetCode
/* Generated */ #else
/* Generated */ TA_RetCode TA_S_BRVR( int    startIdx,
/* Generated */                              int    endIdx,
/* Generated */                              const float  inOpen[],
/* Generated */                              const float  inHigh[],
/* Generated */                              const float  inLow[],
/* Generated */                              const float  inClose[],
/* Generated */                              const float  inVolume[],
/* Generated */                              int          *outBegIdx,
/* Generated */                              int          *outNBElement,
/* Generated */                              double        outBodyRatio[],
/* Generated */                              double        outVolumeRatio[] )
/* Generated */ #endif
/* Generated */ {
/* Generated */     double BodyPeriodTotal, VolumePeriodTotal;
/* Generated */     int i, outIdx, BodyTrailingIdx, VolumeTrailingIdx, lookbackTotal;
/* Generated */  #ifndef TA_FUNC_NO_RANGE_CHECK
/* Generated */  #if defined( _RUST )
/* Generated */     if( endIdx < startIdx ) {
/* Generated */        return ENUM_VALUE(RetCode,TA_OUT_OF_RANGE_END_INDEX,OutOfRangeEndIndex);
/* Generated */     }
/* Generated */  #else
/* Generated */     if( startIdx < 0 ) {
/* Generated */        return ENUM_VALUE(RetCode,TA_OUT_OF_RANGE_START_INDEX,OutOfRangeStartIndex);
/* Generated */     }
/* Generated */     if( (endIdx < 0) || (endIdx < startIdx)) {
/* Generated */        return ENUM_VALUE(RetCode,TA_OUT_OF_RANGE_END_INDEX,OutOfRangeEndIndex);
/* Generated */     }
/* Generated */  #endif
/* Generated */  #if defined( _RUST )
/* Generated */  #else
/* Generated */     #if !defined(_JAVA)
/* Generated */     if(!inOpen||!inHigh||!inLow||!inClose||!inVolume)
/* Generated */        return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */     #endif
/* Generated */     #if !defined(_JAVA)
/* Generated */     if( !outBodyRatio )
/* Generated */        return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */     if( !outVolumeRatio )
/* Generated */        return ENUM_VALUE(RetCode,TA_BAD_PARAM,BadParam);
/* Generated */     #endif
/* Generated */  #endif
/* Generated */  #endif
/* Generated */    lookbackTotal = LOOKBACK_CALL(BRVR)();
/* Generated */    if( startIdx < lookbackTotal )
/* Generated */       startIdx = lookbackTotal;
/* Generated */    if( startIdx > endIdx )
/* Generated */    {
/* Generated */       VALUE_HANDLE_DEREF_TO_ZERO(outBegIdx);
/* Generated */       VALUE_HANDLE_DEREF_TO_ZERO(outNBElement);
/* Generated */       return ENUM_VALUE(RetCode,TA_SUCCESS,Success);
/* Generated */    }
/* Generated */    BodyPeriodTotal = 0;
/* Generated */    VolumePeriodTotal = 0;
/* Generated */    BodyTrailingIdx = startIdx - 10;
/* Generated */    VolumeTrailingIdx = startIdx - 20;
/* Generated */    i = BodyTrailingIdx;
/* Generated */    while( i < startIdx ) {
/* Generated */         BodyPeriodTotal += TA_REALBODY(i);
/* Generated */         i++;
/* Generated */    }
/* Generated */    i = VolumeTrailingIdx;
/* Generated */    while( i < startIdx ) {
/* Generated */         VolumePeriodTotal += inVolume[i];
/* Generated */         i++;
/* Generated */    }
/* Generated */    i = startIdx;
/* Generated */    outIdx = 0;
/* Generated */    do
/* Generated */    {
/* Generated */         double avgBody = BodyPeriodTotal / 10.0;
/* Generated */         double avgVolume = VolumePeriodTotal / 20.0;
/* Generated */         double currentBody = TA_REALBODY(i);
/* Generated */         double bodyRatio;
/* Generated */         if( avgBody > 0 )
/* Generated */             bodyRatio = currentBody / avgBody;
/* Generated */         else
/* Generated */             bodyRatio = 0.0;
/* Generated */         if( TA_CANDLECOLOR(i) == -1 )
/* Generated */             bodyRatio = -bodyRatio;
/* Generated */         double volumeRatio;
/* Generated */         if( avgVolume > 0 )
/* Generated */             volumeRatio = inVolume[i] / avgVolume;
/* Generated */         else
/* Generated */             volumeRatio = 0.0;
/* Generated */         outBodyRatio[outIdx] = bodyRatio;
/* Generated */         outVolumeRatio[outIdx] = volumeRatio;
/* Generated */         outIdx++;
/* Generated */         BodyPeriodTotal += TA_REALBODY(i) - TA_REALBODY(BodyTrailingIdx);
/* Generated */         VolumePeriodTotal += inVolume[i] - inVolume[VolumeTrailingIdx];
/* Generated */         i++;
/* Generated */         BodyTrailingIdx++;
/* Generated */         VolumeTrailingIdx++;
/* Generated */    } while( i <= endIdx );
/* Generated */    VALUE_HANDLE_DEREF(outNBElement) = outIdx;
/* Generated */    VALUE_HANDLE_DEREF(outBegIdx)    = startIdx;
/* Generated */    return ENUM_VALUE(RetCode,TA_SUCCESS,Success);
/* Generated */ }
/* Generated */ 
/**** END GENCODE SECTION 5 - DO NOT DELETE THIS LINE ****/
